import { Link } from 'react-router-dom'

const articles=[['چطور در عدم‌قطعیت تصمیم بگیریم؟','آینده‌پژوهی','وقتی داده‌ها کامل نیستند، کیفیت پرسش مهم‌تر از سرعت پاسخ است.'],['هوش مصنوعی و آینده آموزش','فناوری','پنج تغییری که نقش معلم و تجربه یادگیری را بازتعریف می‌کنند.'],['سازمان به‌مثابه یک سیستم زنده','مدیریت','چرا اصلاح یک بخش، گاهی عملکرد کل سازمان را ضعیف‌تر می‌کند؟']]
const courses=[['تفکر سیستمی برای مدیران','در حال برگزاری','۸ جلسه · آنلاین'],['آینده‌پژوهی کاربردی','ثبت‌نام باز','شروع ۲۴ مهر'],['سواد هوش مصنوعی نوجوانان','برگزار شده','گزارش دوره منتشر شد']]
export function HomePage(){return <>
  <section className="hero"><div className="hero-grid shell"><div className="hero-copy"><span className="eyebrow">مدرسه × اندیشکده × آزمایشگاه</span><h1>آینده را<br/><em>امروز</em> بسازیم.</h1><p>آترا جایی برای فهم پیچیدگی، دیدن امکان‌های آینده و یادگیری مهارت‌هایی است که تصمیم‌های امروز را دقیق‌تر می‌کنند.</p><div className="actions"><Link className="button" to="/register">ثبت‌نام در دوره <b>←</b></Link><Link className="text-link" to="/articles">مشاهده مقالات</Link></div></div><div className="hero-visual" aria-label="نمایش نمادین شبکه یادگیری آترا"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="hero-card"><span>گزارش تازه</span><strong>نقشه مهارت‌های آینده ایران</strong><Link to="/free">دریافت رایگان ←</Link></div><div className="floating-note"><b>+۲۴۰۰</b><span>عضو جامعه یادگیری</span></div></div></div></section>
  <section className="intro shell"><span className="section-index">۰۱ / درباره آترا</span><div><h2>ما پاسخ آماده نمی‌دهیم؛<br/>روش بهتر فکر کردن را تمرین می‌کنیم.</h2><p>آترا پیوندی میان پژوهش و آموزش است. موضوعات پیچیده را به تجربه‌های یادگیری روشن و کاربردی تبدیل می‌کنیم تا نوجوانان، مدیران و سازمان‌ها بتوانند آینده را بهتر ببینند و آگاهانه‌تر عمل کنند.</p><Link className="text-link" to="/about">داستان آترا را بخوانید ←</Link></div></section>
  <section className="section light"><div className="shell"><SectionHead index="۰۲" kicker="خواندنی‌ها" title="ایده‌هایی برای دیدن جهان از زاویه‌ای دیگر" link="/articles"/><div className="article-grid">{articles.map((a,i)=><article className="article-card" key={a[0]}><div className={'article-art art-'+(i+1)}><span>۰{i+1}</span></div><div className="article-body"><small>{a[1]} · {5+i*2} دقیقه مطالعه</small><h3>{a[0]}</h3><p>{a[2]}</p><Link to="/articles">خواندن مقاله ←</Link></div></article>)}</div></div></section>
  <section className="section navy"><div className="shell"><SectionHead index="۰۳" kicker="شنیدنی‌ها" title="پادکست آترا؛ مکثی برای عمیق‌تر شنیدن" link="/podcasts" inverse/><div className="podcast-row">{['آیا آینده قابل پیش‌بینی است؟','ذهن سیستمی چگونه کار می‌کند؟','مدرسه در عصر هوش مصنوعی'].map((x,i)=><article className="podcast-mini" key={x}><button aria-label={'پخش '+x}>▶</button><div><small>اپیزود {String(i+12).padStart(2,'0')} · {24+i*7} دقیقه</small><h3>{x}</h3><div className="wave">▂▅▃▇▂▆▃▅▂▇▃▆▂▅▃▇</div></div></article>)}</div></div></section>
  <section className="section shell"><SectionHead index="۰۴" kicker="مدرسه آترا" title="مسیرهای یادگیری برای ساختن توانایی واقعی" link="/courses"/><div className="course-list">{courses.map((c,i)=><article key={c[0]}><span className={'status s'+i}>{c[1]}</span><div><small>دوره ۰{i+1}</small><h3>{c[0]}</h3></div><p>{c[2]}</p><Link className="circle-link" to="/courses">←</Link></article>)}</div></section>
  <section className="club"><div className="shell club-inner"><div><span className="eyebrow">آترا کلاب</span><h2>یادگیری با پایان دوره تمام نمی‌شود.</h2><p>به جمع دانش‌آموختگان آترا بپیوندید؛ گفت‌وگو کنید، رویدادهای اختصاصی را ببینید و پروژه‌های مشترک بسازید.</p></div><Link className="button yellow" to="/dashboard">ورود به باشگاه</Link></div></section>
  <section className="newsletter shell"><div><small>نامه هفتگی آترا</small><h2>هر هفته، یک ایده ارزش مکث کردن.</h2></div><form onSubmit={e=>{e.preventDefault();localStorage.setItem('atra-newsletter',new FormData(e.currentTarget).get('email') as string);e.currentTarget.reset()}}><label className="sr-only" htmlFor="news-email">ایمیل</label><input id="news-email" name="email" type="email" required placeholder="نشانی ایمیل شما"/><button className="button">عضویت در خبرنامه</button></form></section>
  </>}
function SectionHead({index,kicker,title,link,inverse=false}:{index:string,kicker:string,title:string,link:string,inverse?:boolean}){return <header className={'section-head '+(inverse?'inverse':'')}><div><span>{index} / {kicker}</span><h2>{title}</h2></div><Link className="text-link" to={link}>مشاهده همه ←</Link></header>}
