import { Link } from 'react-router-dom'
import { Reveal } from '../components/Reveal'
import { useLocale } from '../locale/LocaleContext'
import type * as React from 'react'

export function HomePage(){const {isFa}=useLocale()
const articles=isFa?[['چطور در عدم‌قطعیت تصمیم بگیریم؟','آینده‌پژوهی','وقتی داده‌ها کامل نیستند، کیفیت پرسش مهم‌تر از سرعت پاسخ است.'],['هوش مصنوعی و آینده آموزش','فناوری','پنج تغییری که نقش معلم و تجربه یادگیری را بازتعریف می‌کنند.'],['سازمان به‌مثابه یک سیستم زنده','مدیریت','چرا اصلاح یک بخش، گاهی عملکرد کل سازمان را ضعیف‌تر می‌کند؟']]:[['How do you decide under uncertainty?','Foresight','When the data is incomplete, the quality of the question matters more than the speed of the answer.'],['AI and the future of education','Technology','Five changes that will redefine the teacher’s role and the learning experience.'],['The organization as a living system','Management','Why fixing one unit can sometimes weaken the whole organization.']]
const courses=isFa?[['تفکر سیستمی برای مدیران','در حال برگزاری','۸ جلسه · آنلاین'],['آینده‌پژوهی کاربردی','ثبت‌نام باز','شروع ۲۴ مهر'],['سواد هوش مصنوعی نوجوانان','برگزار شده','گزارش دوره منتشر شد']]:[['Systems Thinking for Managers','Running now','8 sessions · Online'],['Applied Foresight','Enrollment open','Starts Oct 16'],['AI Literacy for Teens','Completed','Course report published']]
const faNum=(n:number|string)=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[+d])
const hero=isFa?{eyebrow:'مدرسه × اندیشکده × آزمایشگاه',title:'آینده را<br/><em>امروز</em> بسازیم.',lead:'آترا جایی برای فهم پیچیدگی، دیدن امکان‌های آینده و یادگیری مهارت‌هایی است که تصمیم‌های امروز را دقیق‌تر می‌کنند.',cta:'ثبت‌نام در دوره',articles:'مشاهده مقالات',cardLabel:'گزارش تازه',cardTitle:'نقشه مهارت‌های آینده ایران',cardLink:'دریافت رایگان',stat:'+۲۴۰۰',statLabel:'عضو جامعه یادگیری'}:{eyebrow:'School × Think Tank × Laboratory',title:'Let’s build the<br/><em>future</em> today.',lead:'Atra is a place for understanding complexity, seeing tomorrow’s possibilities, and learning the skills that sharpen today’s decisions.',cta:'Enroll in a course',articles:'Browse articles',cardLabel:'New report',cardTitle:'Iran’s Future-Skills Map',cardLink:'Get the report',stat:'+2,400',statLabel:'Community members'}
const intro=isFa?{index:'۰۱ / درباره آترا',title:'ما پاسخ آماده نمی‌دهیم؛<br/>روش بهتر فکر کردن را تمرین می‌کنیم.',body:'آترا پیوندی میان پژوهش و آموزش است. موضوعات پیچیده را به تجربه‌های یادگیری روشن و کاربردی تبدیل می‌کنیم تا نوجوانان، مدیران و سازمان‌ها بتوانند آینده را بهتر ببینند و آگاهانه‌تر عمل کنند.',link:'داستان آترا را بخوانید'}:{index:'01 / About Atra',title:'We don’t hand out ready answers;<br/>we practice thinking better.',body:'Atra connects research with education. We turn complex topics into clear, hands-on learning experiences so teenagers, managers, and organizations can see the future more clearly and act more deliberately.',link:'Read Atra’s story'}
const reading=isFa?{index:'۰۲',kicker:'خواندنی‌ها',title:'ایده‌هایی برای دیدن جهان از زاویه‌ای دیگر',viewAll:'مشاهده همه',read:'خواندن مقاله',minutes:'دقیقه مطالعه'}:{index:'02',kicker:'Reading',title:'Ideas for seeing the world from another angle',viewAll:'View all',read:'Read article',minutes:'min read'}
const listening=isFa?{index:'۰۳',kicker:'شنیدنی‌ها',title:'پادکست آترا؛ مکثی برای عمیق‌تر شنیدن',viewAll:'مشاهده همه',episodes:['آیا آینده قابل پیش‌بینی است؟','ذهن سیستمی چگونه کار می‌کند؟','مدرسه در عصر هوش مصنوعی'],episodeNo:'اپیزود',minute:'دقیقه',play:'پخش'}:{index:'03',kicker:'Listening',title:'The Atra Podcast: a pause to listen deeper',viewAll:'View all',episodes:['Can the future be predicted?','How does a systems mind work?','School in the age of AI'],episodeNo:'Episode',minute:'min',play:'Play'}
const school=isFa?{index:'۰۴',kicker:'مدرسه آترا',title:'مسیرهای یادگیری برای ساختن توانایی واقعی',viewAll:'مشاهده همه',courseNo:'دوره'}:{index:'04',kicker:'Atra School',title:'Learning paths that build real capability',viewAll:'View all',courseNo:'Course'}
const club=isFa?{eyebrow:'آترا کلاب',title:'یادگیری با پایان دوره تمام نمی‌شود.',body:'به جمع دانش‌آموختگان آترا بپیوندید؛ گفت‌وگو کنید، رویدادهای اختصاصی را ببینید و پروژه‌های مشترک بسازید.',cta:'ورود به باشگاه'}:{eyebrow:'Atra Club',title:'Learning doesn’t end when the course does.',body:'Join Atra’s graduate community — exchange ideas, catch exclusive events, and build projects together.',cta:'Enter the club'}
const news=isFa?{label:'نامه هفتگی آترا',title:'هر هفته، یک ایده ارزش مکث کردن.',email:'ایمیل',placeholder:'نشانی ایمیل شما',cta:'عضویت در خبرنامه'}:{label:'The Atra weekly',title:'Every week, one idea worth pausing for.',email:'Email',placeholder:'Your email address',cta:'Subscribe'}
return <>
  <section className="hero"><div className="hero-grid shell"><div className="hero-copy"><span className="eyebrow hero-enter e1">{hero.eyebrow}</span><h1 className="hero-enter e2" dangerouslySetInnerHTML={{__html:hero.title}}/><p className="hero-enter e3">{hero.lead}</p><div className="actions hero-enter e4"><Link className="button" to="/register">{hero.cta}</Link><Link className="text-link" to="/articles">{hero.articles}</Link></div></div><div className="hero-visual hero-enter e3" aria-label={isFa?'نمایش نمادین شبکه یادگیری آترا':'Symbolic view of the Atra learning network'}><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="hero-card"><span>{hero.cardLabel}</span><strong>{hero.cardTitle}</strong><Link to="/free">{hero.cardLink}</Link></div><div className="floating-note"><b>{hero.stat}</b><span>{hero.statLabel}</span></div></div></div></section>
  <Reveal as="section" className="intro shell"><span className="section-index">{intro.index}</span><div><h2 dangerouslySetInnerHTML={{__html:intro.title}}/><p>{intro.body}</p><Link className="text-link" to="/about">{intro.link}</Link></div></Reveal>
  <Reveal as="section" className="section light"><div className="shell"><SectionHead index={reading.index} kicker={reading.kicker} title={reading.title} link="/articles" viewAll={reading.viewAll}/><div className="article-grid stagger-grid">{articles.map((a,i)=><article className="article-card" key={a[0]} style={{'--i':i} as React.CSSProperties}><div className={'article-art art-'+(i+1)}><span>{isFa?faNum('0'+(i+1)):'0'+(i+1)}</span></div><div className="article-body"><small>{a[1]} · {isFa?faNum(5+i*2):5+i*2} {reading.minutes}</small><h3>{a[0]}</h3><p>{a[2]}</p><Link to="/articles">{reading.read}</Link></div></article>)}</div></div></Reveal>
  <Reveal as="section" className="section navy"><div className="shell"><SectionHead index={listening.index} kicker={listening.kicker} title={listening.title} link="/podcasts" viewAll={listening.viewAll} inverse/><div className="podcast-row stagger-grid">{listening.episodes.map((x,i)=><article className="podcast-mini" key={x} style={{'--i':i} as React.CSSProperties}><button aria-label={listening.play+' '+x}>▶</button><div><small>{listening.episodeNo} {isFa?faNum(String(i+12).padStart(2,'0')):String(i+12).padStart(2,'0')} · {isFa?faNum(24+i*7):24+i*7} {listening.minute}</small><h3>{x}</h3><div className="wave">▂▅▃▇▂▆▃▅▂▇▃▆▂▅▃▇</div></div></article>)}</div></div></Reveal>
  <Reveal as="section" className="section shell"><SectionHead index={school.index} kicker={school.kicker} title={school.title} link="/courses" viewAll={school.viewAll}/><div className="course-list stagger-grid">{courses.map((c,i)=><article key={c[0]} style={{'--i':i} as React.CSSProperties}><span className={'status s'+i}>{c[1]}</span><div><small>{school.courseNo} {isFa?faNum(String(i+1).padStart(2,'0')):String(i+1).padStart(2,'0')}</small><h3>{c[0]}</h3></div><p>{c[2]}</p></article>)}</div></Reveal>
  <Reveal as="section" className="club"><div className="shell club-inner"><div><span className="eyebrow">{club.eyebrow}</span><h2>{club.title}</h2><p>{club.body}</p></div><Link className="button yellow" to="/dashboard">{club.cta}</Link></div></Reveal>
  <Reveal as="section" className="newsletter shell"><div><small>{news.label}</small><h2>{news.title}</h2></div><form onSubmit={e=>{e.preventDefault();localStorage.setItem('atra-newsletter',new FormData(e.currentTarget).get('email') as string);e.currentTarget.reset()}}><label className="sr-only" htmlFor="news-email">{news.email}</label><input id="news-email" name="email" type="email" required placeholder={news.placeholder}/><button className="button">{news.cta}</button></form></Reveal>
  </>}

function SectionHead({index,kicker,title,link,viewAll,inverse=false}:{index:string,kicker:string,title:string,link:string,viewAll:string,inverse?:boolean}){return <header className={'section-head '+(inverse?'inverse':'')}><div><span>{index} / {kicker}</span><h2>{title}</h2></div><Link className="text-link" to={link}>{viewAll}</Link></header>}
