import { useMemo, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'

const articleData=[
  ['چطور در عدم‌قطعیت تصمیم بگیریم؟','آینده‌پژوهی','علی منصوری','۲۲ شهریور ۱۴۰۵','۷ دقیقه','۱٬۸۴۲'],
  ['هوش مصنوعی و آینده آموزش','فناوری','سارا یوسفی','۱۸ شهریور ۱۴۰۵','۹ دقیقه','۲٬۳۱۶'],
  ['سازمان به‌مثابه یک سیستم زنده','مدیریت','محمدرضا توزندجانی','۱۲ شهریور ۱۴۰۵','۶ دقیقه','۱٬۲۲۸'],
  ['اقتصاد توجه؛ منبع کمیاب عصر ما','اقتصاد','مریم شریفی','۰۷ شهریور ۱۴۰۵','۸ دقیقه','۹۷۴'],
  ['مدرسه‌ای برای مسئله‌های واقعی','علوم تربیتی','نیلوفر حاتمی','۲۹ مرداد ۱۴۰۵','۵ دقیقه','۱٬۱۰۹'],
  ['سناریونویسی؛ تمرین دیدن امکان‌ها','آینده‌پژوهی','علی منصوری','۲۱ مرداد ۱۴۰۵','۱۱ دقیقه','۱٬۵۶۳'],
]
const courseData=[
  {title:'تفکر سیستمی برای مدیران',state:'جاری',meta:'۸ جلسه آنلاین · سه‌شنبه‌ها ۱۸ تا ۲۰',desc:'دیدن روابط پنهان، حلقه‌های بازخورد و اهرم‌های تغییر در سازمان.',progress:62},
  {title:'آینده‌پژوهی کاربردی',state:'آینده',meta:'شروع ۲۴ مهر · ۱۰ جلسه',desc:'از رصد روندها تا ساخت سناریو و تصمیم‌گیری در عدم‌قطعیت.',progress:0},
  {title:'سواد هوش مصنوعی نوجوانان',state:'انجام‌شده',meta:'تابستان ۱۴۰۵ · ۶ جلسه',desc:'فهم سازوکار هوش مصنوعی و استفاده خلاق، مسئولانه و ایمن.',progress:100},
]

function PageHero({eyebrow,title,lead}:{eyebrow:string,title:string,lead:string}){return <section className="page-title"><div className="shell"><span>{eyebrow}</span><h1>{title}</h1><p>{lead}</p></div></section>}
function Notice({children}:{children:string}){return <p className="form-notice" role="status">{children}</p>}
function saveForm(key:string,e:FormEvent<HTMLFormElement>,setDone:(x:boolean)=>void){e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;localStorage.setItem(key,JSON.stringify(Object.fromEntries(new FormData(form))));setDone(true);form.reset()}

export function AboutPage(){return <><PageHero eyebrow="ما که هستیم" title="آترا، تمرین دیدن و ساختن آینده" lead="مدرسه و اندیشکده آترا از یک پرسش آغاز شد: چطور می‌توان آموخت که در جهان پیچیده، بهتر فکر کنیم؟"/><section className="content-section shell split"><div><span className="section-index">روایت آترا</span><h2>پژوهش وقتی ارزشمند است که به توانایی عمل تبدیل شود.</h2></div><div className="long-copy"><p>آترا در سال ۱۴۰۲ با تمرکز بر تفکر سیستمی و آینده‌پژوهی شکل گرفت. ما فاصله میان دانش دانشگاهی و مسئله‌های واقعی را با دوره، پژوهش، آزمایش و گفت‌وگو کم می‌کنیم.</p><p>بیانیه ما ساده است: هیچ آینده‌ای از پیش نوشته نشده؛ اما هر انتخاب امروز، دامنه‌ای از آینده‌ها را ممکن یا ناممکن می‌کند.</p></div></section><section className="section light"><div className="shell"><header className="section-head"><div><span>بنیان‌گذاران</span><h2>ترکیب تجربه اجرایی و نگاه آینده‌نگر</h2></div></header><div className="people-grid"><Person initials="مت" name="محمدرضا توزندجانی" role="هم‌بنیان‌گذار و مدیر مدرسه" text="پژوهشگر مدیریت و کارآفرینی؛ با تجربه طراحی مسیرهای یادگیری و مشاوره تحصیلی و شغلی."/><Person initials="عم" name="علی منصوری" role="هم‌بنیان‌گذار و مدیر اندیشکده" text="پژوهشگر سیستم‌ها و آینده‌پژوهی؛ با تجربه طراحی فرآیندهای سازمانی و تحلیل روندهای فناوری."/></div></div></section><section className="section shell"><header className="section-head"><div><span>شورای علمی</span><h2>اساتید و مشاوران همراه</h2></div></header><div className="advisor-list">{[['دکتر مهتاب رستگار','اقتصاد و سیاست‌گذاری'],['دکتر کاوه نیک‌فر','علوم شناختی'],['سارا یوسفی','طراحی تجربه یادگیری'],['امیرحسین نادری','فناوری و هوش مصنوعی']].map((p,i)=><article key={p[0]}><span>۰{i+1}</span><div><h3>{p[0]}</h3><p>{p[1]}</p></div></article>)}</div></section></>}
function Person({initials,name,role,text}:{initials:string,name:string,role:string,text:string}){return <article className="person"><div className="portrait">{initials}</div><small>{role}</small><h3>{name}</h3><p>{text}</p><ul><li>طراحی و راهبری برنامه‌های آموزشی</li><li>پژوهش و اجرای پروژه‌های بین‌رشته‌ای</li></ul></article>}

export function ArticlesPage(){const [q,setQ]=useState('');const [cat,setCat]=useState('همه');const data=useMemo(()=>articleData.filter(a=>(cat==='همه'||a[1]===cat)&&a.join(' ').includes(q)),[q,cat]);return <><PageHero eyebrow="کتابخانه آترا" title="مقالاتی برای دقیق‌تر دیدن" lead="یادداشت‌ها و تحلیل‌هایی درباره مدیریت، اقتصاد، فناوری، آینده‌پژوهی و یادگیری."/><section className="shell filters"><label>جستجو<input value={q} onChange={e=>setQ(e.target.value)} placeholder="عنوان یا نویسنده…"/></label><label>دسته‌بندی<select value={cat} onChange={e=>setCat(e.target.value)}>{['همه','مدیریت','اقتصاد','فناوری','آینده‌پژوهی','علوم تربیتی'].map(x=><option key={x}>{x}</option>)}</select></label><label>مرتب‌سازی<select><option>جدیدترین</option><option>پربازدیدترین</option><option>زمان مطالعه</option></select></label></section><section className="shell library-grid">{data.map((a,i)=><article className="library-card" key={a[0]}><div className={'library-art art-'+((i%3)+1)}><span>{a[1]}</span><button aria-label="ذخیره مقاله" onClick={e=>{e.currentTarget.textContent='✓'}}>♡</button></div><small>{a[3]} · {a[4]}</small><h2>{a[0]}</h2><p>یادداشتی کاربردی برای پیوند دادن مفهوم با تصمیم‌ها و تجربه‌های روزمره.</p><footer><span>{a[2]}</span><span>◉ {a[5]}</span></footer></article>)}</section>{!data.length&&<div className="empty shell">مقاله‌ای با این مشخصات پیدا نشد.</div>}</>}

export function PodcastsPage(){return <><PageHero eyebrow="رادیو آترا" title="ایده‌ها را بشنوید" lead="گفت‌وگوهایی کوتاه و عمیق درباره آینده، یادگیری و تصمیم‌گیری."/><section className="shell featured-podcast"><div className="pod-cover">A<span>13</span></div><div><small>اپیزود تازه · ۳۶ دقیقه</small><h2>ذهن سیستمی چگونه کار می‌کند؟</h2><p>چرا ذهن ما رویدادها را جدا از هم می‌بیند و چطور می‌توان روابط، تأخیرها و پیامدهای ناخواسته را بهتر تشخیص داد؟</p><audio controls preload="none"/><div className="actions"><button className="text-link">دانلود اپیزود ↓</button><span>سرعت پخش از کنترل پلیر قابل تنظیم است</span></div></div></section><section className="section light"><div className="shell episode-list">{['آیا آینده قابل پیش‌بینی است؟','مدرسه در عصر هوش مصنوعی','انتخاب شغل در جهان متغیر','تفکر نقاد با شکاکیت فرق دارد'].map((x,i)=><article key={x}><b>{String(i+12).padStart(2,'0')}</b><button aria-label={'پخش '+x}>▶</button><div><small>{28+i*5} دقیقه · شهریور ۱۴۰۵</small><h3>{x}</h3><p>خلاصه‌ای روشن از ایده‌های کلیدی اپیزود و پرسش‌هایی برای ادامه دادن گفت‌وگو.</p></div><a href="#" download>↓</a></article>)}</div></section><section className="platforms shell"><b>پادکست آترا را دنبال کنید</b><span>Castbox</span><span>Apple Podcasts</span><span>Spotify</span><span>شنوتو</span></section></>}

export function CoursesPage(){const [tab,setTab]=useState('همه');return <><PageHero eyebrow="مدرسه آترا" title="یادگیری برای مسئله‌های واقعی" lead="دوره‌هایی پروژه‌محور با ترکیبی از آموزش، تمرین، بازخورد و جامعه یادگیری."/><div className="shell tabs">{['همه','جاری','آینده','انجام‌شده'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><section className="shell courses-grid">{courseData.filter(c=>tab==='همه'||c.state===tab).map((c,i)=><article className="course-card" key={c.title}><div className="course-no">۰{i+1}</div><span className="status">{c.state}</span><small>{c.meta}</small><h2>{c.title}</h2><p>{c.desc}</p>{c.state==='جاری'&&<><div className="progress"><i style={{width:c.progress+'%'}}/></div><small>{c.progress}٪ مسیر طی شده</small></>}<div className="course-actions"><Link className="button" to="/register">{c.state==='آینده'?'اطلاع‌رسانی کن':c.state==='جاری'?'مشاهده برنامه':'گزارش دوره'}</Link><button className="text-link">سرفصل‌ها</button></div></article>)}</section><FAQ/></>}
function FAQ(){return <section className="faq shell"><span className="section-index">پرسش‌های متداول</span><div>{[['آیا دوره‌ها گواهی دارند؟','بله، پس از انجام پروژه پایانی و حضور مؤثر، گواهی آترا صادر می‌شود.'],['اگر جلسه‌ای را از دست بدهم چه می‌شود؟','ضبط جلسات تا پایان دوره در پنل کاربری در دسترس است.'],['امکان پرداخت اقساطی وجود دارد؟','برای دوره‌های بیشتر از شش جلسه، پرداخت در دو مرحله ممکن است.']].map(x=><details key={x[0]}><summary>{x[0]}</summary><p>{x[1]}</p></details>)}</div></section>}

export function DashboardPage(){return <><PageHero eyebrow="پنل من" title="سلام، همراه آترا" lead="مسیر یادگیری، محتواهای ذخیره‌شده و منابع اختصاصی شما در یک نگاه."/><section className="shell dashboard"><nav><b>نمای کلی</b><span>دوره‌های من</span><span>ذخیره‌شده‌ها</span><span>پروفایل</span></nav><div><div className="stats"><article><b>۲</b><span>دوره ثبت‌نام‌شده</span></article><article><b>۶۲٪</b><span>پیشرفت این ماه</span></article><article><b>۷</b><span>مقاله ذخیره‌شده</span></article></div><article className="current-course"><small>در حال یادگیری</small><h2>تفکر سیستمی برای مدیران</h2><p>جلسه پنجم: الگوهای رفتاری و حلقه‌های بازخورد</p><div className="progress"><i style={{width:'62%'}}/></div><Link className="button" to="/courses">ادامه دوره</Link></article><h2 className="subhead">منابع رایگان شما</h2><div className="resources">{['کتابچه نقشه‌برداری سیستم‌ها','خلاصه جلسه رصد روندها','ویدئو: خطاهای شناختی رایج'].map((x,i)=><article key={x}><span>{['PDF','NOTE','VIDEO'][i]}</span><h3>{x}</h3><button>دریافت ↓</button></article>)}</div></div></section></>}

function LeadForm({kind}:{kind:'login'|'register'|'free'|'contact'}){const [done,setDone]=useState(false);const titles={login:'ورود با کد یک‌بارمصرف',register:'ثبت‌نام در دوره',free:'دریافت رایگان گزارش',contact:'پیام شما'};return <form className="lead-form" onSubmit={e=>saveForm('atra-'+kind,e,setDone)}><h2>{titles[kind]}</h2>{kind==='contact'&&<><label>نام و نام خانوادگی<input name="name" required minLength={3}/></label><label>موضوع<select name="subject"><option>مشاوره دوره</option><option>همکاری پژوهشی</option><option>سایر</option></select></label></>}{kind==='register'&&<><label>نام و نام خانوادگی<input name="name" required minLength={3}/></label><label>انتخاب دوره<select name="course" required><option value="">انتخاب کنید</option>{courseData.map(c=><option key={c.title}>{c.title}</option>)}</select></label></>}<label>شماره همراه<input name="phone" inputMode="tel" pattern="09[0-9]{9}" placeholder="۰۹۱۲۱۲۳۴۵۶۷" required/></label><label>ایمیل<input name="email" type="email" placeholder="name@example.com" required/></label>{kind==='contact'&&<label>پیام<textarea name="message" required minLength={10}/></label>}{kind==='register'&&<label className="check"><input name="consult" type="checkbox"/> درخواست مشاوره پیش از ثبت‌نام</label>}<button className="button" type="submit">{kind==='login'?'ارسال کد ورود':kind==='register'?'ادامه و مشاهده هزینه':kind==='free'?'دریافت فوری':'ارسال پیام'}</button>{done&&<Notice>{kind==='login'?'کد ورود آزمایشی ارسال شد.':'اطلاعات شما با موفقیت ثبت شد.'}</Notice>}<small>با ادامه، قوانین استفاده و حریم خصوصی آترا را می‌پذیرید.</small></form>}
export function LoginPage(){return <section className="form-page"><div className="form-copy"><Link to="/">آترا / بازگشت</Link><span className="eyebrow">حساب کاربری</span><h1>به مسیر یادگیری خود برگردید.</h1><p>با همان شماره همراه و ایمیلی که هنگام ثبت‌نام وارد کردید وارد شوید.</p></div><LeadForm kind="login"/></section>}
export function RegisterPage(){return <section className="form-page"><div className="form-copy"><Link to="/">آترا / بازگشت</Link><span className="eyebrow">پذیرش مدرسه</span><h1>یک مسیر یادگیری تازه شروع کنید.</h1><p>پس از ثبت درخواست، جزئیات هزینه، تخفیف و روش پرداخت نمایش داده می‌شود.</p><ul><li>هفت روز ضمانت بازگشت وجه</li><li>دسترسی به ضبط جلسات</li><li>عضویت در آترا کلاب</li></ul></div><LeadForm kind="register"/></section>}
export function FreeContentPage(){return <section className="free-page"><div className="shell free-grid"><div><span className="eyebrow">هدیه آترا</span><h1>نقشه مهارت‌های آینده ایران</h1><p>گزارشی ۵۰ صفحه‌ای برای شناخت مهارت‌هایی که تا سال ۱۴۱۰ در آموزش، مدیریت و بازار کار ایران اهمیت بیشتری پیدا می‌کنند.</p><ul><li>۱۲ روند اثرگذار بر آینده کار</li><li>۲۴ مهارت کلیدی در چهار خوشه</li><li>پیشنهادهای عملی برای ساخت مسیر یادگیری</li></ul></div><div className="report-cover"><span>گزارش ۱۴۰۵</span><b>نقشه<br/>مهارت‌های<br/>آینده ایران</b><small>مدرسه و اندیشکده آترا</small></div><LeadForm kind="free"/></div></section>}
export function ContactPage(){return <><PageHero eyebrow="ارتباط با آترا" title="گفت‌وگو را شروع کنیم" lead="برای مشاوره دوره‌ها، همکاری پژوهشی یا طراحی برنامه اختصاصی سازمانی با ما در تماس باشید."/><section className="shell contact-grid"><div><h2>راه‌های ارتباطی</h2><dl><dt>تلفن</dt><dd>۰۹۳۷۸۰۱۱۴۲۸</dd><dt>ایمیل</dt><dd>hello@atra.school</dd><dt>ساعات پاسخ‌گویی</dt><dd>شنبه تا چهارشنبه، ۹ تا ۱۷</dd></dl><div className="map">تهران · جلسات حضوری با هماهنگی قبلی</div></div><LeadForm kind="contact"/></section></>}
export function NotFoundPage(){return <section className="not-found"><b>۴۰۴</b><h1>این مسیر به آینده‌ای نمی‌رسد.</h1><p>نشانی صفحه را بررسی کنید یا به خانه آترا برگردید.</p><Link className="button" to="/">بازگشت به خانه</Link></section>}
